---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: k8s-dummy
  name: k8s-dummy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-dummy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-dummy
    spec:
      containers:
        - image: quay.io/mad01/k8s-dummy:v0.2
          imagePullPolicy: Always
          name: k8s-dummy
          args:
            - "-http=0.0.0.0:8080"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100M
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                - name: X-Healthz-Header
                  value: Running 
            initialDelaySeconds: 3
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-dummy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-dummy
  type: ClusterIP

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-dummy
spec:
  maxReplicas: 25
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: k8s-dummy
  targetCPUUtilizationPercentage: 50
